In [1]:
import pandas as pd
import numpy as np

In [2]:
random_array = np.random.rand(5,5)

In [4]:
random_array

array([[0.47934839, 0.37716803, 0.32239909, 0.61318732, 0.20687802],
       [0.51977033, 0.74531588, 0.58218369, 0.43310355, 0.42004265],
       [0.0318697 , 0.9940481 , 0.38060719, 0.2485422 , 0.53721042],
       [0.80585175, 0.90867457, 0.99432837, 0.34893713, 0.92464378],
       [0.94227222, 0.35748017, 0.98495029, 0.87478816, 0.93194094]])

In [5]:
exponential_array = np.exp(random_array)

In [7]:
exponential_array

array([[1.61502169, 1.45814931, 1.38043558, 1.84630681, 1.22983255],
       [1.68164138, 2.10710693, 1.78994284, 1.54203589, 1.52202647],
       [1.03238298, 2.70215095, 1.46317274, 1.28215493, 1.7112266 ],
       [2.23860241, 2.48103191, 2.70290836, 1.41756007, 2.52097007],
       [2.56580486, 1.42972221, 2.67767877, 2.39836717, 2.53943328]])

In [9]:
print("Randome 5*5 Array: ", random_array)
print("\nExponential of each element: ", exponential_array)

Randome 5*5 Array:  [[0.47934839 0.37716803 0.32239909 0.61318732 0.20687802]
 [0.51977033 0.74531588 0.58218369 0.43310355 0.42004265]
 [0.0318697  0.9940481  0.38060719 0.2485422  0.53721042]
 [0.80585175 0.90867457 0.99432837 0.34893713 0.92464378]
 [0.94227222 0.35748017 0.98495029 0.87478816 0.93194094]]

Exponential of each element:  [[1.61502169 1.45814931 1.38043558 1.84630681 1.22983255]
 [1.68164138 2.10710693 1.78994284 1.54203589 1.52202647]
 [1.03238298 2.70215095 1.46317274 1.28215493 1.7112266 ]
 [2.23860241 2.48103191 2.70290836 1.41756007 2.52097007]
 [2.56580486 1.42972221 2.67767877 2.39836717 2.53943328]]
